export const GET_USER_PROFILE__SUCCESS = "GET_USER_PROFILE__SUCCESS";
export const UPDATE_PROFILE__SUCCESS = "UPDATE_PROFILE__SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const REQUEST_FAILURE = "REQUEST_FAILURE";
export const CHANGE_STATE = "CHANGE_STATE";
