version: 2.1 

orbs: 
  coveralls: coveralls/coveralls@1.0.4 


jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
      
    working_directory: ~/champs-frontend
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
            
      - run: npm install
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
      - run: npm run test
      
      - coveralls/upload  